add support for stylelint formatter and vue files
Chiel92/vim-autoformat pull request #309
Opened 2020-07-26 18:32 UTC by oprudkyi

https://stylelint.io/
https://vuejs.org/

2020-07-29 10:16 UTC, Chiel92 commented on plugin/defaults.vim
> +if !exists('g:formatdef_stylelint')
This seems to be copied straight away from the (horrible) ESLint code. If you are certain that you need to do similar things, could you extract the common functionality into shared functions?

2020-07-29 10:25 UTC, Chiel92 commented on plugin/defaults.vim
>  endif
You seem to include generic javascript formatters here. Would any javascript formatter just work for Vue files?

2020-07-29 10:28 UTC, Chiel92 commented on plugin/defaults.vim
> +    function! g:BuildStylelintTmpFile(path, ext)
I don't think it necessary to use tmp files, as stylelint seems to have a --stdin flag: https://github.com/stylelint/stylelint/blob/master/docs/user-guide/usage/cli.md#--stdin

2020-07-29 10:30 UTC, Chiel92 commented on plugin/defaults.vim
> +    function! g:BuildStyleLintCmd()
Is it really necessary to manually find all the config files? It seems you can pass a filename argument, I would expect this to take care of all configuration related things: https://github.com/stylelint/stylelint/blob/master/docs/user-guide/usage/options.md#codefilename

2020-07-29 13:02 UTC, oprudkyi commented
Hi @Chiel92 
yes, sorry, I did it some time ago and without careful research. I am going to rework integration

2020-07-29 13:05 UTC, oprudkyi commented on plugin/defaults.vim
>  endif
vue is a mix of html/js/css/scss https://vuejs.org/v2/guide/single-file-components.html
only eslint (as I know) support it

2020-09-06 09:50 UTC, oprudkyi commented on plugin/defaults.vim
> +    function! g:BuildStyleLintCmd()
reimplemented this part with --stdin and --codefilename

2020-09-06 09:52 UTC, oprudkyi commented
Hi @Chiel92
I've fixed incorrect parts

2020-09-08 09:36 UTC, Chiel92 requested changes
Thanks for your efforts! This looks quite okay right now. Still some small comments to follow up on.

2020-09-08 09:36 UTC, Chiel92 commented on plugin/defaults.vim
> +            return "(>&2 echo 'stylelint not supported on win32')"
Why is stylelint not supported on windows? A quick google suggests that windows _is_ supported.

2020-09-08 09:36 UTC, Chiel92 commented on plugin/defaults.vim
> +        let l:prog = s:NodeJsFindPathToExecFile('stylelint')
Good that this calls a function now.

2020-09-08 09:36 UTC, Chiel92 commented on plugin/defaults.vim
> +        return l:prog." --fix --stdin --stdin-filename ".bufname('%')
You're passing just the filename here. Will that always work, or should you pass the full path?

2020-09-08 12:11 UTC, oprudkyi commented on plugin/defaults.vim
> +            return "(>&2 echo 'stylelint not supported on win32')"
Hi @Chiel92 
unfortunately I don't have access to any windows pc, I suppose there will be needed some other paths and so on, and additional testing that I can't do

2020-09-08 12:26 UTC, oprudkyi commented on plugin/defaults.vim
> +        return l:prog." --fix --stdin --stdin-filename ".bufname('%')
it seems bufname('%') and pwd always provide correct path , and I can't test this when they are different either
also tsfmt and robocop use the same approach

2020-09-15 07:56 UTC, Chiel92 commented on plugin/defaults.vim
> +        return l:prog." --fix --stdin --stdin-filename ".bufname('%')
Allright, let's leave it this way then.

2020-09-15 07:57 UTC, Chiel92 commented on plugin/defaults.vim
> +            return "(>&2 echo 'stylelint not supported on win32')"
I'm on a windows PC, so I can put up the burden of testing.

2020-09-29 11:02 UTC, Chiel92 commented on plugin/defaults.vim
> +            return "(>&2 echo 'stylelint not supported on win32')"
It doesn't seem to work on windows out of the box because the global NPM module path is different from the *nix case. So let's leave that for now.

2020-09-29 11:05 UTC, Chiel92 approved these changes

2020-09-29 11:05 UTC, merged

2020-09-29 11:05 UTC, Chiel92 commented
Let's merge this. Thanks!