Support of running multiple formatters for the same file
Chiel92/vim-autoformat pull request #310
Opened 2020-07-26 19:32 UTC by oprudkyi

Designed for vue files (that contain html/js/css/scss) but can be useful for other file types as well

2020-09-29 11:22 UTC, Chiel92 requested changes
Hi, thanks again for your efforts. Your PR looks good in principal, but there are still some minor comments.

2020-09-29 11:22 UTC, Chiel92 commented on README.md
> +```
There is a typo here. `formaters -> formatters`. But I would prefer a conciser name like `run_all_formatters` anyway.

2020-09-29 11:22 UTC, Chiel92 commented on plugin/autoformat.vim
> +                else
This logic is duplicate to that below. Looks like it could be merged with the logic on line 162 if you get it out of that block.

2020-09-29 11:22 UTC, Chiel92 commented on README.md
> +There is possible to apply multiple formatters for single file, by example, html can use special formatters for js/css etc.
*It is possible

2020-09-29 11:22 UTC, Chiel92 commented on README.md
> +There is possible to apply multiple formatters for single file, by example, html can use special formatters for js/css etc.
by example -> for example

2020-09-29 11:22 UTC, Chiel92 commented on README.md
> +Support can be enabled via `g:enable_multiple_formaters_<identifier>` option.
via *the* ...

2020-09-29 11:22 UTC, Chiel92 commented on README.md
> +In this case, formatters from `g:formatdef_<identifier>` will be applied to file one by one. Fallback (vim) formatting
to *the* file

2020-10-07 22:09 UTC, oprudkyi commented
Hi @Chiel92 
code has been updated

2020-10-08 08:03 UTC, Chiel92 approved these changes

2020-10-08 08:03 UTC, merged

2020-10-08 08:03 UTC, Chiel92 commented
Looking good! Thanks again